version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - aws s3 sync out/ s3://my-nextjs-app-frontend --delete
